name: malia-pro-access
services:
- name: web
  source_dir: /
  github:
    repo: Salon-Boss/malia-pro-access
    branch: main
  run_command: node server-production.js
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "8080"
  - key: SHOPIFY_STORE_DOMAIN
    value: "7b4ae8-00.myshopify.com"
  - key: SHOPIFY_ACCESS_TOKEN
    type: SECRET
    value: "SHOPIFY_TOKEN_TO_BE_SET_IN_DIGITALOCEAN"
  - key: SHOPIFY_SCOPES
    value: "read_products,read_customers,read_collections,read_orders"
  - key: SHOPIFY_APP_URL
    value: "https://shopadmin.maliaextensions.com"
  - key: SHOPIFY_APP_HANDLE
    value: "malia-pro-access"
  - key: VERIFIED_TAG
    value: "verified"
  - key: BUTTERFLY_PAID_TAG
    value: "butterfly_paid"
  - key: CERTIFICATION_URL
    value: "https://maliaextensions.com/pages/certification"
  - key: SESSION_SECRET
    type: SECRET
    value: "malia-pro-access-secret-2024"
  - key: DATABASE_URL
    scope: RUN_TIME
    value: "${malia-pro-access-db.DATABASE_URL}"
databases:
- name: malia-pro-access-db
  engine: PG
  version: "13"
  size: db-s-dev-database
domains:
- domain: shopadmin.maliaextensions.com
  type: PRIMARY
  zone: maliaextensions.com
